version: '3.8'

services:
  api:
    build: ./api
    image: garistvlad/heart-classifier-api:v2
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - "./api:/usr/src/api"
    ports:
      - "8000:8000"