version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
    webserver:
        build:
            context: images/airflow-docker
        image: garistvlad/airflow-docker
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - FERNET_KEY=15BkJoqyLppoEXq0OhDZnIlNepKFf87WFwLbfzqddHO=
            - SMTP_USER=${SMTP_USER}
            - SMTP_PASSWORD=${SMTP_PASSWORD}
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./logs:/usr/local/airflow/logs
            - ./data:/usr/local/airflow/data
            - ./config:/usr/local/airflow/config
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "5050:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
    ml_base:
        build:
            context: images/airflow-ml-base
        image: garistvlad/airflow-ml-base
        restart: "no"
    load_dataset:
        build:
            context: images/airflow-load-dataset
        image: garistvlad/airflow-load-dataset
        restart: "no"
    split_dataset:
        build:
            context: images/airflow-split-dataset
        image: garistvlad/airflow-split-dataset
        restart: "no"
    fit_transformer:
        build:
            context: images/airflow-fit-transformer
        image: garistvlad/airflow-fit-transformer
        restart: "no"
    transform:
        build:
            context: images/airflow-transform
        image: garistvlad/airflow-transform
        restart: "no"
    fit_model:
        build:
            context: images/airflow-fit-model
        image: garistvlad/airflow-fit-model
        restart: "no"
    validate:
        build:
            context: images/airflow-validate
        image: garistvlad/airflow-validate
        restart: "no"
    predict:
        build:
            context: images/airflow-predict
        image: garistvlad/airflow-predict
        restart: "no"
volumes:
  logs: