download_params:
  s3_bucket: "madeawsbucket"
  s3_filepath: "datasets/heart.csv"
  output_folder: "data/raw/"
input_data_path: "data/raw/heart.csv"
output_model_path: "models/model.pkl"
metric_path: "models/metrics.json"
split_params:
  val_size: 0.2
  random_state: 42
  shuffle: true
train_params:
  model_type: "LogisticRegression"
  classifier_params:
    C: 2
    max_iter: 100
    random_state: 42
feature_params:
  binary_features:
    - "sex"
    - "fbs"
    - "exang"
  categorical_features:
    - "cp"
    - "restecg"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_col: "target"